version: "3.7"

services:

  frontend:
    image: store_front:1.0.0
    restart: always
    container_name: frontend
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://localhost:8080
